---
name: "📕 Documentation Issue"
description: Report an issue in documentation
title: "short issue description"
labels: [documentation, needs-triage, bug]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of the issue.
    validations:
      required: true
