name: Set Branch Protection

on:
  push:
    branches:
      - main
      - repair
  workflow_dispatch:

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch protection for main
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/branches/main/protection \
          -d '{
            "required_status_checks": {
              "strict": true,
              "contexts": ["ci/travis"]
            },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": true,
              "required_approving_review_count": 1
            },
            "restrictions": {
              "users": ["octocat"],
              "teams": ["justice-league"]
            },
            "required_linear_history": true,
            "allow_force_pushes": false,
            "allow_deletions": false
          }'
      - name: Set branch protection for repair
        run: |
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/branches/repair/protection \
          -d '{
            "required_status_checks": {
              "strict": true,
              "contexts": ["ci/travis"]
            },
            "enforce_admins": true,
            "required_pull_request_reviews": {
              "dismiss_stale_reviews": true,
              "require_code_owner_reviews": true,
              "required_approving_review_count": 1
            },
            "restrictions": {
              "users": ["octocat"],
              "teams": ["justice-league"]
            },
            "required_linear_history": true,
            "allow_force_pushes": false,
            "allow_deletions": false
          }'