name: Rebase Upstream
on:
  schedule:
  - cron: "0 0 * * 0"  # run once a week
  workflow_dispatch:   # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # fetching all history so i can rebase
        token: ${{ secrets.GH_TOKEN }}
    - name: Configure git for tradeshiftci
      uses: tradeshift/actions-git/configure-from-gpg-key@v1
      with:
        gpg-key: ${{ secrets.TRADESHIFTCI_GPG_KEY }}  
    - uses: tradeshift/rebase-upstream-action@master
